-- 흥덕 업무함 전용 데이터베이스 구조
-- 기존 public 테이블과 데이터를 수정하거나 삭제하지 않습니다.
-- Supabase SQL Editor에서 전체를 한 번에 실행하세요.

create schema if not exists teacher_hub;

create table if not exists teacher_hub.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists teacher_hub.documents (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(trim(title)) between 1 and 200),
  description text check (description is null or char_length(description) <= 1000),
  storage_path text not null unique,
  original_filename text not null,
  mime_type text not null,
  file_size bigint not null check (file_size > 0 and file_size <= 52428800),
  tags text[] not null default '{}',
  is_favorite boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists teacher_hub.document_categories (
  document_id uuid not null references teacher_hub.documents(id) on delete cascade,
  category_id bigint not null references teacher_hub.categories(id) on delete cascade,
  primary key (document_id, category_id)
);

create table if not exists teacher_hub.app_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create or replace function teacher_hub.set_updated_at()
returns trigger
language plpgsql
set search_path = teacher_hub, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function teacher_hub.is_admin()
returns boolean
language sql
stable
security definer
set search_path = teacher_hub, pg_temp
as $$
  select exists (
    select 1 from teacher_hub.app_admins
    where user_id = auth.uid()
  );
$$;

create or replace function teacher_hub.create_document(
  p_title text,
  p_description text,
  p_storage_path text,
  p_original_filename text,
  p_mime_type text,
  p_file_size bigint,
  p_tags text[] default '{}',
  p_category_ids bigint[] default '{}'
)
returns uuid
language plpgsql
security definer
set search_path = teacher_hub, pg_temp
as $$
declare
  new_document_id uuid;
begin
  if char_length(trim(p_title)) < 1 or char_length(trim(p_title)) > 200 then
    raise exception '제목을 확인해 주세요.';
  end if;
  if p_file_size < 1 or p_file_size > 52428800 then
    raise exception '파일은 최대 50MB까지 올릴 수 있어요.';
  end if;
  if p_mime_type not in (
    'application/pdf',
    'application/haansofthwp', 'application/x-hwp',
    'application/vnd.hancom.hwp', 'application/vnd.hancom.hwpx',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'image/jpeg', 'image/png'
  ) then
    raise exception '지원하지 않는 파일 형식이에요.';
  end if;

  insert into teacher_hub.documents (
    title, description, storage_path, original_filename, mime_type, file_size, tags
  ) values (
    trim(p_title), nullif(trim(p_description), ''), p_storage_path,
    p_original_filename, p_mime_type, p_file_size,
    coalesce(array(select distinct trim(tag) from unnest(p_tags) tag where trim(tag) <> ''), '{}')
  )
  returning id into new_document_id;

  insert into teacher_hub.document_categories (document_id, category_id)
  select new_document_id, category_id
  from unnest(coalesce(p_category_ids, '{}')) category_id
  where exists (
    select 1 from teacher_hub.categories
    where id = category_id
  )
  on conflict do nothing;

  return new_document_id;
end;
$$;

drop trigger if exists categories_updated_at on teacher_hub.categories;
create trigger categories_updated_at
before update on teacher_hub.categories
for each row execute function teacher_hub.set_updated_at();

drop trigger if exists documents_updated_at on teacher_hub.documents;
create trigger documents_updated_at
before update on teacher_hub.documents
for each row execute function teacher_hub.set_updated_at();

insert into teacher_hub.categories (name, sort_order) values
  ('담임', 1),
  ('평가', 2),
  ('생기부', 3),
  ('입시·진로', 4),
  ('학교양식', 5),
  ('기타', 6)
on conflict (name) do nothing;

alter table teacher_hub.categories enable row level security;
alter table teacher_hub.documents enable row level security;
alter table teacher_hub.document_categories enable row level security;
alter table teacher_hub.app_admins enable row level security;

revoke all on schema teacher_hub from anon, authenticated;
revoke all on all tables in schema teacher_hub from anon, authenticated;
revoke all on all sequences in schema teacher_hub from anon, authenticated;
revoke all on all routines in schema teacher_hub from anon, authenticated;

grant usage on schema teacher_hub to anon, authenticated;
grant select on teacher_hub.categories, teacher_hub.documents, teacher_hub.document_categories
  to anon, authenticated;
grant insert, update, delete on teacher_hub.categories, teacher_hub.documents, teacher_hub.document_categories
  to authenticated;
grant usage, select on all sequences in schema teacher_hub to authenticated;
grant execute on function teacher_hub.create_document(text, text, text, text, text, bigint, text[], bigint[])
  to anon, authenticated;
grant execute on function teacher_hub.is_admin() to anon, authenticated;

create policy "teacher_hub_categories_public_read"
on teacher_hub.categories for select to anon, authenticated
using (true);

create policy "teacher_hub_categories_admin_insert"
on teacher_hub.categories for insert to authenticated
with check (teacher_hub.is_admin());

create policy "teacher_hub_categories_admin_update"
on teacher_hub.categories for update to authenticated
using (teacher_hub.is_admin())
with check (teacher_hub.is_admin());

create policy "teacher_hub_categories_admin_delete"
on teacher_hub.categories for delete to authenticated
using (teacher_hub.is_admin());

create policy "teacher_hub_documents_public_read"
on teacher_hub.documents for select to anon, authenticated
using (deleted_at is null or teacher_hub.is_admin());

create policy "teacher_hub_documents_admin_insert"
on teacher_hub.documents for insert to authenticated
with check (teacher_hub.is_admin());

create policy "teacher_hub_documents_admin_update"
on teacher_hub.documents for update to authenticated
using (teacher_hub.is_admin())
with check (teacher_hub.is_admin());

create policy "teacher_hub_documents_admin_delete"
on teacher_hub.documents for delete to authenticated
using (teacher_hub.is_admin());

create policy "teacher_hub_links_public_read"
on teacher_hub.document_categories for select to anon, authenticated
using (true);

create policy "teacher_hub_links_admin_insert"
on teacher_hub.document_categories for insert to authenticated
with check (teacher_hub.is_admin());

create policy "teacher_hub_links_admin_update"
on teacher_hub.document_categories for update to authenticated
using (teacher_hub.is_admin())
with check (teacher_hub.is_admin());

create policy "teacher_hub_links_admin_delete"
on teacher_hub.document_categories for delete to authenticated
using (teacher_hub.is_admin());

create policy "teacher_hub_admins_read_self"
on teacher_hub.app_admins for select to authenticated
using (user_id = auth.uid());

-- Storage 정책은 먼저 Dashboard에서 teacher-work-hub 버킷을 만든 다음 적용됩니다.
create policy "teacher_hub_files_public_upload"
on storage.objects for insert to anon, authenticated
with check (bucket_id = 'teacher-work-hub');

create policy "teacher_hub_files_admin_update"
on storage.objects for update to authenticated
using (bucket_id = 'teacher-work-hub' and teacher_hub.is_admin())
with check (bucket_id = 'teacher-work-hub' and teacher_hub.is_admin());

create policy "teacher_hub_files_admin_delete"
on storage.objects for delete to authenticated
using (bucket_id = 'teacher-work-hub' and teacher_hub.is_admin());
